import { entry, param } from './define';
import type { Reader, RegistrySlice } from './types';

/** Seconds per simulation tick. Both environments step at 30 Hz, and a test checks it against the racing SIM_DT. */
export const TICK_DT = 1 / 30;

const any = (name: string, summary: string) => param(name, 'number', '*', summary);

/**
 * Math that works the same in every environment and both block scopes. None
 * of these read the world, so constant arguments fold at compile time.
 */
export const CORE_SLICE: RegistrySlice = {
  env: 'core',
  entries: [
    entry({
      name: 'abs',
      kind: 'function',
      scope: 'both',
      env: 'core',
      type: 'number',
      unit: '*',
      params: [any('value', 'Any number.')],
      summary: 'The size of a number without its sign.',
      description: 'Turns negative numbers positive and leaves positive ones alone. Handy when only the size of an error matters, not its direction.',
      example: 'let wobble = abs(rand() - 0.5)',
      block: { category: 'math', label: 'abs {value}' },
      explain: 'the size of {value}',
      binding: { kind: 'fn', call: ([a]) => (v, io) => Math.abs(a(v, io)), fold: ([a]) => Math.abs(a) },
    }),
    entry({
      name: 'min',
      kind: 'function',
      scope: 'both',
      env: 'core',
      type: 'number',
      unit: '*',
      params: [any('a', 'First number.'), any('b', 'Second number, in the same unit.')],
      summary: 'The smaller of two numbers.',
      description: 'Returns whichever of the two numbers is smaller. Both must have the same unit.',
      example: 'let low = min(rand(), 0.5)',
      block: { category: 'math', label: 'smaller of {a} and {b}' },
      explain: 'the smaller of {a} and {b}',
      binding: { kind: 'fn', call: ([a, b]) => (v, io) => Math.min(a(v, io), b(v, io)), fold: ([a, b]) => Math.min(a, b) },
    }),
    entry({
      name: 'max',
      kind: 'function',
      scope: 'both',
      env: 'core',
      type: 'number',
      unit: '*',
      params: [any('a', 'First number.'), any('b', 'Second number, in the same unit.')],
      summary: 'The larger of two numbers.',
      description: 'Returns whichever of the two numbers is larger. Both must have the same unit.',
      example: 'let high = max(rand(), 0.5)',
      block: { category: 'math', label: 'larger of {a} and {b}' },
      explain: 'the larger of {a} and {b}',
      binding: { kind: 'fn', call: ([a, b]) => (v, io) => Math.max(a(v, io), b(v, io)), fold: ([a, b]) => Math.max(a, b) },
    }),
    entry({
      name: 'clamp',
      kind: 'function',
      scope: 'both',
      env: 'core',
      type: 'number',
      unit: '*',
      params: [any('value', 'The number to limit.'), any('low', 'Smallest allowed value.'), any('high', 'Largest allowed value.')],
      summary: 'Keeps a number between a low and a high limit.',
      description: 'Returns the value, raised to the low limit if it is below it and lowered to the high limit if it is above it. All three must share a unit.',
      example: 'let safe = clamp(rand(), 0.2, 0.8)',
      block: { category: 'math', label: 'clamp {value} between {low} and {high}' },
      explain: '{value} kept between {low} and {high}',
      binding: {
        kind: 'fn',
        call: ([x, lo, hi]) => (v, io) => Math.min(Math.max(x(v, io), lo(v, io)), hi(v, io)),
        fold: ([x, lo, hi]) => Math.min(Math.max(x, lo), hi),
      },
    }),
    entry({
      name: 'sqrt',
      kind: 'function',
      scope: 'both',
      env: 'core',
      type: 'number',
      unit: 'sqrt',
      params: [any('value', 'A number that is zero or more.')],
      summary: 'The square root of a number.',
      description: 'Returns the number that, multiplied by itself, gives the value. The unit is halved too, so the root of square meters is meters. Negative values give zero.',
      example: 'let root = sqrt(rand())',
      block: { category: 'math', label: 'square root of {value}' },
      explain: 'the square root of {value}',
      binding: { kind: 'fn', call: ([a]) => (v, io) => Math.sqrt(Math.max(0, a(v, io))), fold: ([a]) => Math.sqrt(Math.max(0, a)) },
    }),
    entry({
      name: 'sign',
      kind: 'function',
      scope: 'both',
      env: 'core',
      type: 'number',
      unit: '',
      params: [any('value', 'Any number.')],
      summary: 'Minus one, zero or one, following the sign of a number.',
      description: 'Returns 1 for positive numbers, -1 for negative ones and 0 for zero. The result has no unit.',
      example: 'let side = sign(rand() - 0.5)',
      block: { category: 'math', label: 'sign of {value}' },
      explain: 'the sign of {value}',
      binding: { kind: 'fn', call: ([a]) => (v, io) => Math.sign(a(v, io)), fold: ([a]) => Math.sign(a) },
    }),
    entry({
      name: 'rand',
      kind: 'function',
      scope: 'both',
      env: 'core',
      type: 'number',
      unit: '',
      cost: 3,
      summary: 'A random number from 0 up to 1.',
      description:
        'Returns a new random number each time it runs, at least 0 and below 1. It is seeded, so a replay draws exactly the same numbers. Each agent has its own sequence in each tick.',
      example: 'let coin = rand()',
      block: { category: 'math', label: 'random number' },
      explain: 'a random number between 0 and 1',
      binding: {
        kind: 'fn',
        call: (_args, ctx) => {
          const holder = ctx.rng;
          return (() => holder.rng.next()) as Reader;
        },
      },
    }),
    entry({
      name: 'pi',
      kind: 'constant',
      scope: 'both',
      env: 'core',
      type: 'number',
      unit: 'rad',
      summary: 'Half a turn, about 3.14159 radians.',
      description: 'The angle of half a full turn, in radians. Use it with angle sensors, such as pi / 4 for an eighth of a turn.',
      example: 'let eighth = pi / 4',
      block: { category: 'math', label: 'pi' },
      explain: 'half a turn',
      binding: { kind: 'const', value: Math.PI },
    }),
    entry({
      name: 'dt',
      kind: 'constant',
      scope: 'tick',
      env: 'core',
      type: 'number',
      unit: 's',
      summary: 'Seconds per tick, 1/30.',
      description: 'How much time one tick covers. Multiply a per second rate by dt to get the amount for one tick.',
      example: 'reward 0.5 * dt / 1 s',
      block: { category: 'math', label: 'tick length' },
      explain: 'the length of one tick',
      binding: { kind: 'const', value: TICK_DT },
    }),
  ],
};
